version: '3'
networks:
  default: {}
services:
  mysql:
    container_name: ${REPO_NAME}_mysql
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 6033:3306 # LOCAL_PORT:DOCKER_PORT
    environment:
      MYSQL_DATABASE: ${REPO_NAME}_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
    env_file: .env

  server:
    container_name: ${REPO_NAME}_server
    build:
      context: ./server
    ports:
      - "8082:80" # LOCAL_PORT:DOCKER_PORT
    volumes:
      - ${SOURCE_PATH}:/var/www/${REPO_NAME}
      - ./docker/${REPO_NAME}/apache/logs:/var/log/httpd
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env

volumes:
  datastore: {}
  cache: {}

