version: '3'
networks:
  default: {}
services:
  mysql:
    container_name: chicongst_mysql
    image: mysql:5.6
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: cclocaldb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "false"
  admin:
    container_name: cc_admin
    build:
      context: ./admin
    ports:
      - "69:80"
    volumes:
      - ${ADMIN_SOURCE_PATH}:/var/www/html/cc_admin
      - ./admin/apache/logs:/var/log/httpd
    links:
      - mysql
    depends_on:
      - mysql
    env_file: .env
  smtp:
    container_name: docker_smtp
    image: schickling/mailcatcher
    ports:
      - 1090:1080

volumes:
  datastore: {}
  cache: {}

